### ISSUE TITLE
Sometimes output stalls

### ISSUE THREAD

**Issue by phahulin** [poanetwork/hydrabadger#3] opened 2018-07-20 16:05 UTC
Sometimes all peers start to repeat every 3 seconds
```
2018-07-20T19:02:09 [INFO] - State: ConnectedValidator(4)
2018-07-20T19:02:09 [INFO] - Generating and inputting 40 random transactions...
```

without producing any batches
```
2018-07-20T19:00:14 [INFO] - NEW STEP OUTPUT:
2018-07-20T19:00:14 [INFO] -     BATCH: 
Batch { epoch: 75, contributions:...
...
```
There doesn't seem to be any errors and I can't reliably reproduce it.

**Comment by c0gent** [comment] 2018-07-20 16:08
Do you see any `BatchDeserializationFailed` errors in any of the logs?

**Comment by c0gent** [comment] 2018-07-24 14:35
Update: Stalling still occurring but we're narrowing down the cause.

**Comment by phahulin** [comment] 2018-07-24 14:36
:+1:

**Comment by c0gent** [comment] 2018-07-28 23:01
Looks like @afck may have found and fixed the cause of the stalling: https://github.com/poanetwork/hbbft/commit/b3bf9e6f2ef279422fe41bc774c7593ddf3f5d32. 

We're now tracking down the source of a memory leak/buffer growth problem. There are also a few other known issues with node connection (especially during keygen) that I will be fixing next week.

I'll close this for now. Thanks and please let me know if you run into anything else.

**Closed by c0gent** 2018-07-28 23:01 UTC
